"""Mask cleanup and GeoTIFF export module for Geo Evidence Engine.

Performs deterministic morphological filtering and connected-component noise removal
on binary change masks without AI models. Exports cleaned masks to GeoTIFF while
strictly preserving CRS, affine transform, dimensions, and metadata.
"""

import os
from typing import Any, Dict, Optional, Union
import cv2
import numpy as np
import rasterio
from rasterio.crs import CRS
from rasterio.transform import Affine


def clean_binary_mask(
    mask: np.ndarray,
    min_patch_size: int = 3,
    kernel_size: int = 3,
    morphology_op: str = "opening",
) -> np.ndarray:
    """Perform deterministic noise cleanup on a binary change mask.

    Args:
        mask: 2D binary numpy array (0=unchanged, 1=changed).
        min_patch_size: Minimum connected component area in pixels. Patches smaller
                        than this size are removed as noise. Set to 0 or 1 to disable.
        kernel_size: Kernel dimension for morphological filtering (e.g., 3 for 3x3).
                     Set to 0 or 1 to disable morphological filtering.
        morphology_op: Morphological operation ('opening', 'closing', 'open_close', 'none').
                       'opening': removes isolated pixel noise (salt).
                       'closing': fills small holes inside change regions (pepper).
                       'open_close': opening followed by closing.

    Returns:
        np.ndarray: Cleaned binary mask of uint8 (0 or 1).
    """
    if mask.ndim != 2:
        raise ValueError(f"Expected 2D binary mask, got ndim={mask.ndim}")

    cleaned = (mask > 0).astype(np.uint8)

    # 1. Morphological filtering
    op_lower = morphology_op.lower().strip() if morphology_op else "none"
    if kernel_size > 1 and op_lower != "none":
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (kernel_size, kernel_size))

        if op_lower == "opening":
            cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_OPEN, kernel)
        elif op_lower == "closing":
            cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_CLOSE, kernel)
        elif op_lower == "open_close":
            cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_OPEN, kernel)
            cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_CLOSE, kernel)
        elif op_lower == "close_open":
            cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_CLOSE, kernel)
            cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_OPEN, kernel)
        else:
            raise ValueError(
                f"Unsupported morphology_op '{morphology_op}'. "
                "Choose 'opening', 'closing', 'open_close', or 'none'."
            )

    # 2. Connected-component area filtering (noise removal)
    if min_patch_size > 1 and np.any(cleaned > 0):
        num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(
            cleaned, connectivity=8
        )
        for label_idx in range(1, num_labels):
            area = stats[label_idx, cv2.CC_STAT_AREA]
            if area < min_patch_size:
                cleaned[labels == label_idx] = 0

    return (cleaned > 0).astype(np.uint8)


def save_mask_to_geotiff(
    mask: np.ndarray,
    output_path: str,
    transform: Affine,
    crs: CRS,
    nodata: Optional[int] = 0,
    metadata: Optional[Dict[str, Any]] = None,
) -> str:
    """Save binary change mask as a georeferenced single-band GeoTIFF.

    Preserves CRS, geotransform, dimensions, and attaches metadata.

    Args:
        mask: 2D numpy array with uint8 binary values (0 or 1).
        output_path: Target filepath for the output GeoTIFF.
        transform: Affine geotransform matrix.
        crs: Coordinate Reference System.
        nodata: Nodata value for the GeoTIFF (default is 0, or None).
        metadata: Optional dictionary of metadata tags to embed in the TIFF.

    Returns:
        str: Absolute filepath of the saved GeoTIFF.
    """
    if mask.ndim != 2:
        raise ValueError(f"Expected 2D mask array, got ndim={mask.ndim}")

    abs_path = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(abs_path), exist_ok=True)

    height, width = mask.shape

    profile = {
        "driver": "GTiff",
        "height": height,
        "width": width,
        "count": 1,
        "dtype": rasterio.uint8,
        "crs": crs,
        "transform": transform,
        "compress": "deflate",
    }
    if nodata is not None:
        profile["nodata"] = nodata

    with rasterio.open(abs_path, "w", **profile) as dst:
        dst.write(mask.astype(np.uint8), 1)

        tags = {
            "DESCRIPTION": "Binary Change Mask generated by SatQuery Geo Evidence Engine",
            "ENGINE": "deterministic",
        }
        if metadata:
            for k, v in metadata.items():
                tags[str(k).upper()] = str(v)

        dst.update_tags(**tags)

    return abs_path
